import './ext-style.css';

export default {
    POMMENT_LOADING: 'Initializing Pomment ...',
    POMMENT_LOADING_FAILED: 'Failed to initialize Pomment. ',
    POMMENT_LOADING_RETRY: 'Retry?',
    POMMENT_REPLYING: 'You are replying {{name}}\'s comment.',
    FORM_NAME: 'Nickname',
    FORM_EMAIL_REQUIRED: 'Email*',
    FORM_WEBSITE: 'Website',
    FORM_CONTENT_REQUIRED: 'Content* (Up to {{maxChar}} characters)',
    FORM_SUBMIT: 'Submit',
    FORM_SUBMITTING: 'Submitting...',
    FORM_CANCEL: 'Cancel',
    FORM_EMPTY_EMAIL: 'Email address is empty',
    FORM_EMPTY_CONTENT: 'Content is empty',
    FORM_BAD_EMAIL: 'Email address is invaild',
    FORM_BAD_CONTENT: 'Content length shouldn\'t be more than {{maxChar}} characters',
    FORM_RECAPTCHA_NOT_READY: 'reCAPTCHA frontend is not ready, please try again later',
    FORM_SUBMIT_ERROR: 'An error occurred while submitting the comment',
    TIME_NOW: 'Just now',
    TIME_SECOND: '{{ago}} seconds ago',
    TIME_MINUTE: '{{ago}} minutes ago',
    TIME_HOUR: '{{ago}} hours ago',
    TIME_DAY: '{{ago}} days ago',
    TIME_WEEK: '{{ago}} weeks ago',
    TIME_MONTH: '{{ago}} months ago',
    ENTRY_ADMIN: 'MOD',
    ENTRY_REPLY: 'Reply',
    ENTRY_REPLY_OF: '(Replied to {{parentName}})',
};
